Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2018-07, with the labels that each got.

#4 docs(dropdown): Custom action in usage tab
  server/documents/modules/dropdown.html.eco
Labels: Can Merge, Typo

#5 docs(dropdown): Extend sortSelect option explanation
  server/documents/modules/dropdown.html.eco
Labels: Can Merge, New Content

#11 Add documentation for disabled rating trough class
  server/documents/modules/rating.html.eco
Labels: New Content
