Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2018-10, with the labels that each got.

#28 Fix form dropdown js example code
  server/documents/collections/form.html.eco
Labels: Confirmed Bug

#29 include fomantic* in HTML
  server/documents/introduction/getting-started.html.eco
Labels: Typo

#33 [Toast] Color Variants
  server/documents/modules/toast.html.eco
Labels: New Content

#32 feat(calendar): add disabled state doc
  server/documents/modules/calendar.html.eco
Labels: New Content

#30 [Toast] New enhancements
  server/documents/modules/toast.html.eco
Labels: New Content

#40 Removed SUI Ads widget
  server/partials/header.html.eco
Labels: Correction

#39 [Dimmer] Examples for partially dimmer
  server/documents/modules/dimmer.html.eco
Labels: New Content

#42 [Calendar] Some Examples did not work
  server/documents/modules/calendar.html.eco
Labels: Confirmed Bug

#41 Changed Semantic to Fomantic at related places.
  README.md
  server/documents/cla.html.eco
  server/documents/collections/grid.html.eco
  server/documents/elements/container.html.eco
  server/documents/elements/icon.html.eco
  server/documents/elements/image.html.eco
  server/documents/globals/reset.html.eco
  server/documents/globals/site.html.eco
  server/documents/index.html.eco
  server/documents/introduction/advanced-usage.html.eco
  server/documents/introduction/build-tools.html.eco
  server/documents/introduction/getting-started.html.eco
  server/documents/introduction/glossary.html.eco
  server/documents/introduction/integrations.html.eco
  server/documents/modules/nag.html.eco
  server/documents/modules/popup.html.eco
  server/documents/modules/tab.html.eco
  server/documents/usage/layout.html.eco
  server/documents/views/card.html.eco
  server/files/stylesheets/library/basic.icon.css
Labels: Correction
