Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2019-02, with the labels that each got.

#84 [Icons] update icons to FontAwesome 5.7
  server/documents/elements/icon.html.eco
Labels: New Content

#87 [Rating] Fixed all examples of rating to use the new syntax
  server/documents/collections/table.html.eco
  server/documents/modules/popup.html.eco
  server/documents/views/card.html.eco
  server/partials/examples/card.html
  server/partials/examples/popup.html
  server/partials/examples/rating.html
Labels: Fix

#67 Feat: Icon alias search
  server/files/javascript/icon.js
Labels: New Content, On Hold

#97 [Checkbox] Indeterminate toggle example
  server/documents/modules/checkbox.html.eco
  server/files/javascript/checkbox.js
Labels: New Content

#98 [Grid] Widescreen example was defined as large screen
  server/documents/collections/grid.html.eco
Labels: Typo

#99 [Modal] Missing settings documented
  server/documents/modules/modal.html.eco
Labels: Correction

#100 [Modal] overlay fullscreen modal example
  server/documents/modules/modal.html.eco
Labels: New Content

#101 [Modal] Normal fullscreen example was opening new overlay example aswell
  server/documents/modules/modal.html.eco
Labels: Fix
