Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2019-11, with the labels that each got.

#177 [Table] Marked rows or cells example
  server/documents/collections/table.html.eco
Labels: New Content

#173 [Progress] new keepState Parameter added
  server/documents/modules/progress.html.eco
Labels: New Content

#172 feat(icons): update icons to FA 5.11.2
  server/documents/elements/icon.html.eco
Labels: New Content

#168 [Dropdown] preventing change trigger option explained
  server/documents/modules/dropdown.html.eco
Labels: New Content

#167 [Dropdown] show and hide behavior parameters explanation
  server/documents/modules/dropdown.html.eco
Labels: Missing Content, New Content

#166 [Calendar] Infos for new onBeforeChange andold onChange callbacks
  server/documents/modules/calendar.html.eco
Labels: New Content

#165 [Calendar] type and date as data attributes example
  server/documents/modules/calendar.html.eco
  server/files/javascript/calendar.js
Labels: New Content

#160 feat(form): Generalize form states
  server/documents/collections/form.html.eco
Labels: New Content

#171 feat(calendar): added missing append selector and short info about usage
  server/documents/modules/calendar.html.eco
Labels: Missing Content

#176 feat(emoji): add docs page for emoji component
  server/documents/elements/emoji.html.eco
  server/documents/usage/theming.html.eco
  server/files/javascript/emoji.js
  server/files/javascript/emoji_strategy.js
  server/files/stylesheets/docs.css
  server/layouts/basic.html.eco
  server/partials/ui-css.html.eco
Labels: New Content

#174 feat(toast): add new feature examples and updates settings documentation
  server/documents/modules/toast.html.eco
  server/files/javascript/toast.js
Labels: New Content

#178 fix(emoji): button to add more emojis to category
  server/files/javascript/emoji.js
Labels: Confirmed Bug, Correction

#179 feat(slider): add interpretLabel example and setting example setting
  server/documents/modules/slider.html.eco
Labels: Missing Content, New Content

#181 feat(build-tools): add missing components
  server/documents/introduction/build-tools.html.eco
Labels: Missing Content

#180 feat(emoji): adjusted docs to match autosizing emojis
  server/documents/elements/emoji.html.eco
  server/files/javascript/emoji.js
Labels: New Content
