Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2019-07, with the labels that each got.

#139 Add required variables to example theme.config
  server/documents/usage/theming.html.eco
Labels: Correction

#138 [Calendar] Typo Fix
  server/documents/modules/calendar.html.eco
Labels: Typo

#137 feat(checkbox): docs for new setting enableEnterKey
  server/documents/modules/checkbox.html.eco
Labels: New Content

#141 [Form Validation] Be consistent with 'identifier' naming
  server/documents/behaviors/form.html.eco
Labels: Correction

#147 fix(popup): Fixed default values and missing content.
  server/documents/modules/popup.html.eco
Labels: Correction

#151 fix(message): Missing closing tag
  server/documents/collections/message.html.eco
Labels: Fix

#148 fix(api): added missing callback parameters in response example
  server/documents/behaviors/api.html.eco
Labels: Correction

#146 fix(form): Corrected anchor link to dropdown multiple reference
  server/documents/collections/form.html.eco
Labels: Confirmed Bug

#150 Better description for add errors
  server/documents/behaviors/form.html.eco
Labels: enhancement

#145 [Dropdown] Explanation and examples of dynamic image and icon values
  server/documents/modules/dropdown.html.eco
Labels: New Content

#143 fix(table): Make colored state a unique section id
  server/documents/collections/table.html.eco
Labels: Confirmed Bug

#144 [Form Validation] Adjusted new , missing or even wrong settings
  server/documents/behaviors/form.html.eco
Labels: Correction, New Content

#153 [Popup] Added new forcePosition setting
  server/documents/modules/popup.html.eco
Labels: New Content

#129 Misswriting on dividing header
  server/documents/modules/slider.html.eco
Labels: Fix

#149 fix(visibility): Moved inifinite scroll to end of page for better usability and fixed wrong closing tag
  server/documents/behaviors/visibility.html.eco
Labels: enhancement
