Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2019-05, with the labels that each got.

#124 [Dropdown] Corrected old renamed behavior
  server/documents/modules/dropdown.html.eco
Labels: Correction

#125 feat(breadcrumb): add inverted variant example
  server/documents/collections/breadcrumb.html.eco
Labels: New Content

#119 feat(calendar): add eventDates examples and onSelect callback setting
  server/documents/modules/calendar.html.eco
Labels: New Content

#121 feat(segment): add horizontally, vertically fitted variant examples
  server/documents/elements/segment.html.eco
Labels: New Content

#122 fix(dropdown): bottom pointing example didn't show on mobile
  server/documents/modules/dropdown.html.eco
Labels: Fix

#112 fix(modal): inverted dimmer example showed two modals
  server/documents/modules/modal.html.eco
Labels: Fix

#113 fix(calendar): missing closing brace in formatter example
  server/documents/modules/calendar.html.eco
Labels: Fix

#118 feat(form): add dirty/clean state example and documentation
  server/documents/behaviors/form.html.eco
  server/files/javascript/validate-form.js
Labels: New Content

#120 feat(search): add a search to the index page
  server/documents/index.html.eco
  server/files/stylesheets/docs.css
  server/layouts/homepage.html.eco
Labels: New Content

#128 feat(*): make headers visible anchors
  server/files/javascript/docs.js
  server/files/stylesheets/docs.css
Labels: New Content

#127 feat(icons): update to FA 5.8.2
  server/documents/elements/icon.html.eco
Labels: New Content

#131 feat(form): add date field and date handling examples in validation
  server/documents/behaviors/form.html.eco
  server/documents/collections/form.html.eco
  server/files/javascript/form.js
  server/files/javascript/validate-form.js
Labels: Missing Content

#132 fix(index): search wasn't visible when fixed at top while scrolling
  server/files/stylesheets/docs.css
Labels: Fix
