Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2019-01, with the labels that each got.

#70 [List] Example of Suffixed ordered list
  server/documents/elements/list.html.eco
Labels: New Content

#71 [Transition] Added new setting skipInlineHidden
  server/documents/modules/transition.html.eco
Labels: New Content

#72 [Label] Right icon should have correct margin when placed after text
  server/documents/elements/label.html.eco
Labels: New Content

#75 [Label] Aligned floating label example
  server/documents/elements/label.html.eco
Labels: New Content

#82 [Dropdown,Search] Added examples for dropdown and search option 'ignoreDiacritics'
  server/documents/modules/dropdown.html.eco
  server/documents/modules/search.html.eco
Labels: New Content

#83 Added Social Twitter link and made FUI Version for Tweet dynamic
  server/documents/index.html.eco
  server/partials/footer.html
Labels: Correction, New Content

#81 [Modal] Added option "scrollbarWidth" to settings tab
  server/documents/modules/modal.html.eco
Labels: New Content

#80 [Segment] Added new "stackable horizontal segments" example
  server/documents/elements/segment.html.eco
Labels: New Content

#79 [Modal] Added new "restoreFocus" option
  server/documents/modules/modal.html.eco
Labels: New Content

#78 [Label] Added bottom floating label example
  server/documents/elements/label.html.eco
Labels: New Content

#85 [Accordion] add nested initialization message
  server/documents/modules/accordion.html.eco
Labels: New Content

#86 [Site] Updated less.js to 3.9.0 so dynamic theme changer works again
  server/files/javascript/library/less.js
  server/files/javascript/library/less.min.js
Labels: Fix
