Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2020-11, with the labels that each got.

#241 fix(emoji): typo correction
  server/documents/elements/emoji.html.eco
Labels: Typo

#242 feat(slider): new option fireChange
  server/documents/modules/slider.html.eco
Labels: New Content

#243 fix(dropdown): incorrect format in example code of selector settings
  server/documents/modules/dropdown.html.eco
Labels: Fix
