Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2020-04, with the labels that each got.

#203 Add example for individual components in semantic.json
  server/documents/introduction/build-tools.html.eco
Labels: New Content

#208 fix(segment): wrap vertical segment example into a separate div to make first-child work
  server/documents/elements/segment.html.eco
Labels: Confirmed Bug

#205 fix (doc) : the default value of minCharacters settings is 0 not 1.
  server/documents/modules/dropdown.html.eco
Labels: Correction
