Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2020-09, with the labels that each got.

#223 feat(form): adjusted behaviors
  server/documents/behaviors/form.html.eco
Labels: Correction, enhancement

#225 [Dropdown] Scrollhint infos
  server/documents/modules/dropdown.html.eco
  server/files/javascript/dropdown.js
Labels: New Content

#226 [Dropdown] vertical item example
  server/documents/modules/dropdown.html.eco
Labels: New Content

#228 fix(getting-started): script tag src and link tag href are incorrect
  server/documents/introduction/getting-started.html.eco
Labels: Fix

#229 fix(jsfiddle): support dashes and underscores in jsfiddle usernames
  server/raw/jsfiddle/index.html
Labels: Fix

#230 [Checkbox] Right aligned examples
  server/documents/modules/checkbox.html.eco
Labels: New Content

#232 [Dropdown] added displaytype setting
  server/documents/modules/dropdown.html.eco
Labels: New Content

#231 fix(input): typo error
  server/documents/elements/input.html.eco
Labels: Typo

#233 feat(dropdown): add the `preventChangeTrigger` parameter for the `set selected` behavior
  server/documents/modules/dropdown.html.eco
Labels: enhancement
