Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2020-02, with the labels that each got.

#197 [Dropdown] added example for data-text preserve on select conversion
  server/documents/modules/dropdown.html.eco
Labels: New Content

#193 feat(form): added settings info for required fields
  server/documents/behaviors/form.html.eco
Labels: New Content

#194 [Modal] Added info about "inside" class for close icons
  server/documents/modules/modal.html.eco
Labels: New Content

#195 [Popup] Added info about "fixed" class for popup widths
  server/documents/modules/popup.html.eco
Labels: New Content

#196 [Dropdown] Added example for unfilterable items
  server/documents/modules/dropdown.html.eco
Labels: New Content

#190 Fixed example for grid alignment
  server/documents/collections/grid.html.eco
Labels: Fix

#198 feat(table): rowspanned example
  server/documents/collections/table.html.eco
Labels: New Content

#191 Update README.md
  README.md
Labels: enhancement
