Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2021-08, with the labels that each got.

#214 fix(calendar): reflect the changes to the calendar module
  server/documents/modules/calendar.html.eco
Labels: New Content, On Hold

#184 fix(flag): emoji flag and sizing example
  server/documents/elements/flag.html.eco
  server/files/javascript/flag.js
Labels: New Content

#299 feat(flag): update version reference
  server/documents/elements/flag.html.eco
Labels: Correction

#301 feat(toast): new centered position
  server/documents/modules/toast.html.eco
Labels: New Content

#300 feat(chore): remove "new" status from toast, slider, emoji
  server/documents/elements/emoji.html.eco
  server/documents/modules/slider.html.eco
  server/documents/modules/toast.html.eco
Labels: enhancement

#294 feat(dropdown): new default value for forceSelection
  server/documents/modules/dropdown.html.eco
Labels: Correction

#302 fix(icon): arrow functions do not work on IE11
  server/files/javascript/icon.js
Labels: Confirmed Bug

#296 feat(form): new default value for fulltextsearch
  server/documents/modules/dropdown.html.eco
Labels: Correction

#297 feat(dropdown): new default value for showonfocus
  server/documents/modules/dropdown.html.eco
Labels: Correction

#305 feat(form): hint to always show messages
  server/documents/collections/form.html.eco
Labels: enhancement

#306 fix(chore): remove cookie link
  server/partials/library-javascript.html.eco
Labels: enhancement

#303 fix(emoji): fix anchor link generation
  server/documents/elements/emoji.html.eco
  server/files/javascript/emoji.js
Labels: Confirmed Bug

#304 fix(modal): hint for autoclosing on actions
  server/documents/modules/modal.html.eco
Labels: Missing Content

#295 feat(form): new default value for errorFocus
  server/documents/behaviors/form.html.eco
Labels: Correction
