Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2021-06, with the labels that each got.

#281 feat(segment): added horizontal equal width example
  server/documents/elements/segment.html.eco
Labels: New Content

#280 feat(dimmer,dropdown,modal,popup): individual show/hide transition
  server/documents/modules/dimmer.html.eco
  server/documents/modules/dropdown.html.eco
  server/documents/modules/modal.html.eco
  server/documents/modules/popup.html.eco
Labels: New Content

#277 fix(build): improved install instructions
  server/documents/introduction/getting-started.html.eco
Labels: enhancement

#282 feat(input): added examples for labeled dropdown
  server/documents/elements/input.html.eco
Labels: New Content

#283 fix(footer): codefund is no more
  server/partials/footer.html
Labels: Correction

#284 fix(libs): upgraded libs, removed unused libs
  server/documents/modules/tab.html.eco
  server/files/javascript/docs.js
  server/files/javascript/emoji.js
  server/files/javascript/icon.js
  server/files/javascript/library/clipboard.js
  server/files/javascript/library/clipboard.min.js
  server/files/javascript/library/cookie.js
  server/files/javascript/library/cookie.min.js
  server/files/javascript/library/detect.js
  server/files/javascript/library/detect.min.js
  server/files/javascript/library/jquery.js
  server/files/javascript/library/jquery.min.js
  server/files/javascript/library/less.js
  server/files/javascript/library/less.min.js
  server/files/javascript/library/sinon.js
Labels: dependencies, enhancement

#285 fix(chore): slashes in anchorpoints let into console error
  server/files/javascript/docs.js
Labels: Confirmed Bug

#286 fix(all): spelling fixes
  server/documents/collections/grid.html.eco
  server/documents/elements/rail.html.eco
  server/documents/modules/embed.html.eco
  server/documents/modules/popup.html.eco
Labels: Typo

#287 feat(modal): dynamic and js template examples and settings
  server/documents/modules/modal.html.eco
Labels: New Content

#288 fix(toast): container html info broke examples
  server/documents/modules/toast.html.eco
Labels: Fix

#291 fix(calendar): 2 digits date notation for safari support
  server/documents/modules/calendar.html.eco
Labels: Fix
