Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2021-01, with the labels that each got.

#254 feat(calendar): disabled month and years example
  server/documents/modules/calendar.html.eco
Labels: Missing Content

#252 feat(message): center and right aligned example
  server/documents/collections/message.html.eco
Labels: New Content

#253 feat(modal): center aligned variant example
  server/documents/modules/modal.html.eco
Labels: New Content

#255 feat(toast): added template and horizontal example
  server/documents/modules/toast.html.eco
Labels: New Content

#256 feat(dropdown): submenu support in values example
  server/documents/modules/dropdown.html.eco
Labels: New Content

#258 feat(toast): attached and center aligned examples
  server/documents/modules/toast.html.eco
Labels: New Content

#259 feat(toast): added html layout info and context setting
  server/documents/modules/toast.html.eco
Labels: Missing Content, New Content

#257 feat(nag): refactored nag site
  server/documents/modules/nag.html.eco
  server/files/javascript/nag.js
Labels: New Content

#260 fix(dropdown) Fixes remoteData example and adds missing behaviour
  server/documents/modules/dropdown.html.eco
Labels: Correction, Missing Content
