Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2022-09, with the labels that each got.

#363 fix(chore): jquery 3.6.1 update and legacy remove
  server/files/javascript/library/jquery.js
  server/files/javascript/library/jquery.legacy.js
  server/files/javascript/library/jquery.legacy.min.js
  server/files/javascript/library/jquery.min.js
  server/layouts/basic.html.eco
  server/layouts/homepage.html.eco
Labels: enhancement

#364 feat(toast, modal): short $. notation
  server/documents/modules/modal.html.eco
  server/documents/modules/toast.html.eco
  server/files/javascript/docs.js
  server/files/javascript/emoji.js
  server/files/javascript/icon.js
  server/files/javascript/new.js
  server/files/javascript/toast.js
Labels: enhancement

#365 refactor(sidebar): remove un-used legacy code
  server/documents/modules/sidebar.html.eco
Labels: Correction

#361 feat(flyout): flyout's module doc
  package-lock.json
  server/documents/modules/flyout.html.eco
  server/files/javascript/docs.js
  server/files/javascript/flyout.js
  server/layouts/default.html.eco
  server/partials/demo-flyout.html
Labels: New Content

#368 fix(chore): replace non working remote apis
  server/documents/modules/dropdown.html.eco
  server/documents/modules/search.html.eco
  server/files/javascript/docs.js
  server/files/javascript/new.js
  server/partials/examples/search.html
  server/raw/animals.json
  server/raw/categories.json
Labels: Fix

#369 feat(flyout): short $. notation
  server/documents/modules/flyout.html.eco
Labels: Correction

#370 feat(modal): basic header, left actions
  server/documents/modules/modal.html.eco
Labels: New Content

#371 feat(flyout): pusher and config templates info
  server/documents/modules/flyout.html.eco
Labels: New Content

#372 fix(popup): clarify closable setting to match code
  server/documents/modules/popup.html.eco
Labels: Correction

#373 feat(flyout): centered, left, basic, blurring, autoFocus,etc.
  server/documents/modules/flyout.html.eco
  server/documents/modules/modal.html.eco
  server/documents/modules/sidebar.html.eco
  server/partials/demo-flyout.html
Labels: New Content

#374 fix(checkbox): some missing behaviors
  server/documents/modules/checkbox.html.eco
Labels: Missing Content

#376 feat(dropdown): actionable example and missing settings
  server/documents/modules/dropdown.html.eco
  server/files/javascript/docs.js
  server/partials/ui-css.html.eco
  server/partials/ui-javascript.html.eco
Labels: New Content
