Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2022-08, with the labels that each got.

#359 chore(cleanup): remove unused code, allow pinch zoom
  server/files/fonts/lato/Lato-Bold.eot
  server/files/fonts/lato/Lato-Bold.ttf
  server/files/fonts/lato/Lato-Bold.woff
  server/files/fonts/lato/Lato-Bold.woff2
  server/files/fonts/lato/Lato-BoldItalic.eot
  server/files/fonts/lato/Lato-BoldItalic.ttf
  server/files/fonts/lato/Lato-BoldItalic.woff
  server/files/fonts/lato/Lato-BoldItalic.woff2
  server/files/fonts/lato/Lato-Italic.eot
  server/files/fonts/lato/Lato-Italic.ttf
  server/files/fonts/lato/Lato-Italic.woff
  server/files/fonts/lato/Lato-Italic.woff2
  server/files/fonts/lato/Lato-Regular.eot
  server/files/fonts/lato/Lato-Regular.ttf
  server/files/fonts/lato/Lato-Regular.woff
  server/files/fonts/lato/Lato-Regular.woff2
  server/files/javascript/customize.js
  server/files/javascript/docs.js
  server/files/javascript/home.js
  server/files/javascript/library/clipboard.js
  server/files/javascript/library/clipboard.min.js
  server/files/javascript/library/jquery.hotkeys.js
  server/files/javascript/library/jquery.hotkeys.min.js
  server/files/javascript/playground.js
  server/files/stylesheets/customize.css
  server/files/stylesheets/docs.css
  server/files/stylesheets/library/basic.icon.css
  server/files/stylesheets/library/docco.css
  server/files/stylesheets/library/fonts/icons.eot
  server/files/stylesheets/library/fonts/icons.svg
  server/files/stylesheets/library/fonts/icons.ttf
  server/files/stylesheets/library/fonts/icons.woff
  server/files/stylesheets/library/sidr.css
  server/files/stylesheets/library/snap.css
  server/files/stylesheets/reset.css
  server/layouts/basic.html.eco
  server/layouts/default.html.eco
  server/layouts/homepage.html.eco
  server/partials/language-modal.html
  server/partials/languages.html
  server/partials/meta.html.eco
  server/partials/transifex.html.eco
  server/raw/humans.txt
  server/raw/images/gif/multi-shortcuts.gif
  server/raw/images/logos/arrowhead.png
  server/raw/images/logos/big-buck.png
  server/raw/images/logos/sunset.png
  server/raw/images/setup/install.gif
  server/raw/jsfiddle/index.html
  server/raw/swf/clipboard.swf
Labels: enhancement

#353 feat(table): scrolling and stuck variant
  server/documents/collections/table.html.eco
  server/documents/elements/container.html.eco
  server/documents/elements/segment.html.eco
Labels: New Content

#357 feat(dropdown): added stuck addition variation
  server/documents/modules/dropdown.html.eco
Labels: New Content

#360 fix(chore): corrected debug defaults
  server/documents/modules/accordion.html.eco
  server/documents/modules/calendar.html.eco
  server/documents/modules/checkbox.html.eco
  server/documents/modules/dimmer.html.eco
  server/documents/modules/dropdown.html.eco
  server/documents/modules/embed.html.eco
  server/documents/modules/modal.html.eco
  server/documents/modules/popup.html.eco
  server/documents/modules/progress.html.eco
  server/documents/modules/rating.html.eco
  server/documents/modules/search.html.eco
  server/documents/modules/shape.html.eco
  server/documents/modules/sidebar.html.eco
  server/documents/modules/sticky.html.eco
  server/documents/modules/tab.html.eco
  server/documents/modules/transition.html.eco
Labels: Correction

#362 fix(search, accordion): fix easing info
  server/documents/modules/accordion.html.eco
  server/documents/modules/search.html.eco
Labels: Correction
