Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2022-10, with the labels that each got.

#380 fix(chore): update links to latest jquery 3.6.1
  server/documents/introduction/getting-started.html.eco
Labels: enhancement

#378 fix(dropdown): missing search class
  server/documents/modules/dropdown.html.eco
  server/partials/examples/dropdown.html
Labels: Correction

#377 feat(chore): global css reduce infos
  server/documents/elements/emoji.html.eco
  server/documents/elements/flag.html.eco
  server/documents/elements/icon.html.eco
  server/documents/introduction/build-tools.html.eco
Labels: Missing Content, enhancement

#381 fix(chore): cleanup js errors
  server/documents/modules/tab.html.eco
  server/files/javascript/calendar.js
  server/files/javascript/docs.js
  server/files/javascript/icon.js
  server/files/javascript/new.js
  server/files/javascript/slider.js
  server/files/javascript/sticky.js
  server/files/javascript/tab.js
  server/files/javascript/visibility.js
  server/raw/metadata.json
Labels: Confirmed Bug, hacktoberfest-accepted

#382 fix(chore): anchors in hidden tabs, js fixes
  README.md
  server/documents/elements/button.html.eco
  server/files/javascript/docs.js
  server/files/javascript/visibility.js
Labels: Fix

#383 feat(chore): 2.9.0 news page
  docpad.coffee
  package.json
  server/documents/behaviors/api.html.eco
  server/documents/behaviors/form.html.eco
  server/documents/behaviors/state.html.eco
  server/documents/collections/grid.html.eco
  server/documents/collections/menu.html.eco
  server/documents/elements/button.html.eco
  server/documents/elements/flag.html.eco
  server/documents/elements/image.html.eco
  server/documents/elements/input.html.eco
  server/documents/elements/rail.html.eco
  server/documents/globals/reset.html.eco
  server/documents/index.html.eco
  server/documents/introduction/advanced-usage.html.eco
  server/documents/introduction/glossary.html.eco
  server/documents/introduction/new.html.eco
  server/documents/modules/accordion.html.eco
  server/documents/modules/embed.html.eco
  server/documents/modules/nag.html.eco
  server/documents/modules/search.html.eco
  server/documents/modules/tab.html.eco
  server/documents/modules/toast.html.eco
  server/documents/modules/transition.html.eco
  server/documents/usage/theming.html.eco
  server/documents/views/advertisement.html.eco
  server/documents/views/card.html.eco
  server/files/javascript/docs.js
  server/files/javascript/library/state.js
  server/files/stylesheets/docs.css
  server/partials/header.html.eco
  server/partials/library-javascript.html.eco
  server/partials/site-menu.html.eco
  server/raw/jsfiddle/index.html
Labels: New Content

#393 fix(form): added a missed HTML close tag
  server/documents/behaviors/form.html.eco
Labels: Correction

#391 fix(progress): better understanding of multiple example
  server/documents/modules/progress.html.eco
Labels: enhancement
