Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2023-03, with the labels that each got.

#439 feat(calendar): event date tooltip colors
  server/documents/modules/calendar.html.eco
Labels: enhancement

#442 feat(chore): jquery 3.6.4 upgrade
  server/documents/introduction/getting-started.html.eco
  server/files/javascript/library/jquery.js
  server/files/javascript/library/jquery.min.js
Labels: dependencies

#441 feat(multi): missing sizing variant examples
  server/documents/elements/divider.html.eco
  server/documents/elements/segment.html.eco
  server/documents/modules/search.html.eco
  server/documents/views/card.html.eco
Labels: Missing Content

#440 feat(slider): minRange, maxRange, restrictedLabels, tooltip
  server/documents/modules/popup.html.eco
  server/documents/modules/slider.html.eco
  server/files/javascript/slider.js
Labels: New Content

#443 feat(chore): color reducing via variation.variables instead of colors
  server/documents/introduction/build-tools.html.eco
Labels: enhancement

#444 feat(label): bottom and center ribbon example
  server/documents/elements/label.html.eco
Labels: New Content

#446 feat(gettingstarted): info about classname order
  server/documents/introduction/getting-started.html.eco
Labels: enhancement

#445 feat(toast): missing settings
  server/documents/modules/toast.html.eco
Labels: Missing Content

#447 feat(search): onResults fromCache
  server/documents/modules/search.html.eco
Labels: enhancement

#448 feat(menu): equal width variant
  server/documents/collections/menu.html.eco
Labels: enhancement

#449 feat(chore): generate new and word order labels from data attribute
  server/documents/behaviors/form.html.eco
  server/documents/behaviors/visibility.html.eco
  server/documents/collections/breadcrumb.html.eco
  server/documents/collections/form.html.eco
  server/documents/collections/grid.html.eco
  server/documents/collections/menu.html.eco
  server/documents/collections/message.html.eco
  server/documents/collections/table.html.eco
  server/documents/elements/button.html.eco
  server/documents/elements/container.html.eco
  server/documents/elements/divider.html.eco
  server/documents/elements/header.html.eco
  server/documents/elements/icon.html.eco
  server/documents/elements/image.html.eco
  server/documents/elements/input.html.eco
  server/documents/elements/label.html.eco
  server/documents/elements/list.html.eco
  server/documents/elements/loader.html.eco
  server/documents/elements/placeholder.html.eco
  server/documents/elements/segment.html.eco
  server/documents/elements/step.html.eco
  server/documents/elements/text.html.eco
  server/documents/globals/site.html.eco
  server/documents/index.html.eco
  server/documents/introduction/build-tools.html.eco
  server/documents/introduction/getting-started.html.eco
  server/documents/introduction/new.html.eco
  server/documents/modules/accordion.html.eco
  server/documents/modules/calendar.html.eco
  server/documents/modules/dimmer.html.eco
  server/documents/modules/dropdown.html.eco
  server/documents/modules/embed.html.eco
  server/documents/modules/flyout.html.eco
  server/documents/modules/modal.html.eco
  server/documents/modules/nag.html.eco
  server/documents/modules/popup.html.eco
  server/documents/modules/progress.html.eco
  server/documents/modules/rating.html.eco
  server/documents/modules/search.html.eco
  server/documents/modules/shape.html.eco
  server/documents/modules/sidebar.html.eco
  server/documents/modules/slider.html.eco
  server/documents/modules/tab.html.eco
  server/documents/modules/toast.html.eco
  server/documents/modules/transition.html.eco
  server/documents/views/advertisement.html.eco
  server/documents/views/card.html.eco
  server/documents/views/comment.html.eco
  server/documents/views/feed.html.eco
  server/documents/views/item.html.eco
  server/documents/views/statistic.html.eco
  server/files/javascript/docs.js
  server/files/javascript/search.js
  server/files/stylesheets/docs.css
  server/files/stylesheets/home.css
  server/layouts/default.html.eco
Labels: enhancement

#452 feat(flags): add alias for czech
  server/files/javascript/flag.js
Labels: enhancement

#451 feat(chore): improved central "newin" label generation
  server/documents/behaviors/form.html.eco
  server/documents/behaviors/visibility.html.eco
  server/documents/elements/label.html.eco
  server/documents/introduction/getting-started.html.eco
  server/documents/modules/calendar.html.eco
  server/documents/modules/dimmer.html.eco
  server/documents/modules/dropdown.html.eco
  server/documents/modules/modal.html.eco
  server/documents/modules/popup.html.eco
  server/documents/modules/search.html.eco
  server/documents/modules/sticky.html.eco
  server/documents/modules/toast.html.eco
  server/documents/views/feed.html.eco
  server/files/javascript/docs.js
  server/files/stylesheets/docs.css
Labels: enhancement

#453 fix(flag): czech_republic
  server/files/javascript/flag.js
Labels: Confirmed Bug

#450 feat(dropdown): keepsearchterm example
  server/documents/modules/dropdown.html.eco
  server/files/javascript/dropdown.js
Labels: New Content

#454 fix(text,tab,index): core infos and page fixes
  server/documents/elements/text.html.eco
  server/documents/index.html.eco
  server/documents/introduction/glossary.html.eco
  server/files/javascript/tab.js
Labels: enhancement
