Repository fomantic/Fomantic-UI-Docs, pull requests merged in 2024-12, with the labels that each got.

#521 feat(chore): remove unused remaining carbon ads code
  server/files/stylesheets/docs.css
  server/files/stylesheets/home.css
  server/partials/tab-header.html.eco
Labels: enhancement

#527 fix(search): missing function parameters for templates
  server/documents/modules/search.html.eco
Labels: Missing Content

#524 feat(calendar): document usage scope of format tokens
  server/documents/modules/calendar.html.eco
Labels: New Content

#523 feat(build): custom output filename
  server/documents/introduction/build-tools.html.eco
Labels: New Content
